# Generated by Django 5.1.15 on 2026-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "import run",
                "verbose_name_plural": "import runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(choices=[("NEXO", "Nexo Portal")], max_length=32),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "transaction",
                    models.CharField(choices=[("SALE", "Sale"), ("RENT", "Rent")], max_length=8),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                ("bathrooms", models.PositiveSmallIntegerField(default=0)),
                ("parking_spaces", models.PositiveSmallIntegerField(default=0)),
                ("area_m2", models.PositiveIntegerField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["source", "external_id"], name="idx_property_source_ext"),
                    models.Index(fields=["city", "transaction"], name="idx_property_city_trans"),
                ],
            },
        ),
    ]
